import ninjascroll from './images/ninja1.jpg';
import akira from './images/akira1.jpg';
import arrietty from './images/arrietty.jpeg';
import howls from './images/howls.jpeg';
import spiritedaway from './images/spiritedaway.jpeg';
import totoro from './images/totoro1.jpg';
import evangelion from './images/evangelion.jpg';
import cowboybebop from './images/cowboybebop.jpg';


export default function getGallery() {
    return [
      { id: 'ninjascroll', name: 'Ninja Scroll', videoId: "yaXJI339uQs", cover: ninjascroll, details:'In this anime film, Jubei, a highly skilled ninja, is coerced into slaying his own clan of warriors. After begrudgingly killing his fellow swordsmen, he becomes a roving hired assassin. During his travels, he must face off against an organization of demonic ninjas known as the Devils of Kimon, who are plotting to take power of Japan\'s government. The Devils will stop at nothing, and have the power to annihilate entire villages. Now, only Jubei and a shogun spy named Dakuan can stop them.'},
      { id: 'akira', name: 'Akira', videoId: "NCmVrn2gnRs", cover: akira, details: 'In 1988 the Japanese government drops an atomic bomb on Tokyo after ESP experiments on children go awry. In 2019, 31 years after the nuking of the city, Kaneda, a bike gang leader, tries to save his friend Tetsuo from a secret government project. He battles anti-government activists, greedy politicians, irresponsible scientists and a powerful military leader until Tetsuo\'s supernatural powers suddenly manifest. A final battle is fought in Tokyo Olympiad exposing the experiment\'s secrets.'},
      { id: 'arrietty', name: 'Arrietty', videoId: "KzBBIBSi2Vo", cover: arrietty, details: 'Arrietty, a tiny teenager, lives with her parents in the recesses of a suburban home, unbeknown to the homeowner and housekeeper. Like others of her kind, Arrietty remains hidden from her human hosts, but occasionally ventures forth from beneath the floorboards to borrow sugar cubes and other supplies. A secret friendship forms when 12-year-old Shawn meets Arrietty, but their relationship could spell danger for Arrietty\'s family.'},
      { id: 'howlsmovingcastle', name: 'Howl\'s Moving Castle', videoId: "iwROgK94zcM", cover: howls, details: 'Sophie (Emily Mortimer) has an uneventful life at her late father\'s hat shop, but all that changes when she befriends wizard Howl (Christian Bale), who lives in a magical flying castle. However, the evil Witch of Waste (Lauren Bacall) takes issue with their budding relationship and casts a spell on young Sophie, which ages her prematurely. Now Howl must use all his magical talents to battle the jealous hag and return Sophie to her former youth and beauty.'},
      { id: 'spiritedaway', name: 'Spirited Away', videoId: "ByXuk9QqQkk", cover: spiritedaway, details: 'In this animated feature by noted Japanese director Hayao Miyazaki, 10-year-old Chihiro (Rumi Hiiragi) and her parents (Takashi Naitô, Yasuko Sawaguchi) stumble upon a seemingly abandoned amusement park. After her mother and father are turned into giant pigs, Chihiro meets the mysterious Haku (Miyu Irino), who explains that the park is a resort for supernatural beings who need a break from their time spent in the earthly realm, and that she must work there to free herself and her parents.'},
      { id: 'myneighbourtotoro', name: 'My Neighbour Totoro', videoId: "pU8BRWhj9_o", cover: totoro, details: 'This acclaimed animated tale by director Hayao Miyazaki follows schoolgirl Satsuke and her younger sister, Mei, as they settle into an old country house with their father and wait for their mother to recover from an illness in an area hospital. As the sisters explore their new home, they encounter and befriend playful spirits in their house and the nearby forest, most notably the massive cuddly creature known as Totoro.'},
      { id: 'cowboybebop', name: 'Cowboy Bepop - The Movie', videoId: "Au1AO1xaEts", cover: cowboybebop, details: 'Cocky Spike Spiegel and the crew of his spaceship, Bebop, an intrepid band of bounty hunters, land on Mars in the year 2071 chasing an enormous cash reward. The four-person team, also including looming cyborg Jet Black, fearless Faye Valentine and tech expert Edward, are in search of ex-military officer Vincent. The former hero has become a biological terrorist with an arsenal of devastating nano-bots that he\'ll let loose on Alba City on the night before Halloween if his demands aren\'t met.' },
      { id: 'evangelion', name: 'The End of Evangelion', videoId: "IQrXRBh94IA", cover: evangelion, details: 'The End of Evangelion is the second film in the Neon Genesis Evangelion franchise, and the last anime release for the series until the Rebuild of Evangelion tetralogy. The film is an alternate ending to the TV series, taking place after episode 24. The film was released on July 19, 1997.' },
    ];
  } 